[settings]
use_ai_validation = true
min_volume = 100000
max_spread = 0.3
timeframes = ["5m", "15m", "1h", "4h"]

[strategies.ssl_ema]
enabled = true

[strategies.trend_meter_ema_atr]
enabled = true

[strategies.squeeze_momentum_atr]
enabled = true

[strategies.supertrend_qqe_trend_a]
enabled = true
